# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0d945c3c89ad3cb179620c08dda36c26"
name = "wishlist-weavers"
handle = "wishlist-weavers"
application_url = "https://tribes-retention-attribute-loving.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "apptestweavers.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tribes-retention-attribute-loving.trycloudflare.com/auth/callback",
  "https://tribes-retention-attribute-loving.trycloudflare.com/auth/shopify/callback",
  "https://tribes-retention-attribute-loving.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
